name: Node.js Package
on:
  push:
jobs:
  test_and_deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v1
      - run: bun install
      - run: bun test
      - run: bun run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOCKEN}}
